In [1]:
import numpy as np

In [2]:
#vector maths
a = np.array([[1,3,],[2,3]])
b= np.array([[2,4],[5,2]])
print (a)
print (b)

[[1 3]
 [2 3]]
[[2 4]
 [5 2]]


In [3]:
#dot product
np.dot(a,b)

array([[17, 10],
       [19, 14]])

In [4]:
#cross product
np.cross(a,b)

array([ -2, -11])

In [5]:
# Transpose
np.transpose(a)

array([[1, 2],
       [3, 3]])

In [8]:
a.T #It also returns the transpose

array([[1, 2],
       [3, 3]])

In [9]:
# Indexing and slicinig in 1D array
a = np.array([11,22,33,44,55,56])
a

array([11, 22, 33, 44, 55, 56])

In [10]:
a[3]

44

In [11]:
#slicing
a[::2]

array([11, 33, 55])

In [14]:
# SLicing and indexing in 2D array
b = np.random.randint(1,20,(5,5))
b

array([[ 5,  4, 19, 11,  2],
       [ 6, 19,  2,  8,  3],
       [17,  2,  8, 11,  9],
       [12,  6,  8,  1, 15],
       [ 8,  3, 19, 16, 15]])

In [17]:
b[2,3] # indexing --> var[row index , col index]

11

In [20]:
b[2] # it will print the row elements in index 2 (it is default for only row !!!)

array([17,  2,  8, 11,  9])

In [21]:
#Slicing --> var[strat , stop1 , step]
#row slicing 
b[0:2:1]

array([[ 5,  4, 19, 11,  2],
       [ 6, 19,  2,  8,  3]])

In [22]:
#column slicing
b[0:3:1]

array([[ 5,  4, 19, 11,  2],
       [ 6, 19,  2,  8,  3],
       [17,  2,  8, 11,  9]])

In [23]:
#slicing --> var[row slicing , col slicing]
b

array([[ 5,  4, 19, 11,  2],
       [ 6, 19,  2,  8,  3],
       [17,  2,  8, 11,  9],
       [12,  6,  8,  1, 15],
       [ 8,  3, 19, 16, 15]])

In [25]:
b[1:2:1 , 1:4:1]

array([[19,  2,  8]])

In [39]:
#all rows and even columns
b[::1 , ::2]

array([[ 5, 19,  2],
       [ 6,  2,  3],
       [17,  8,  9],
       [12,  8, 15],
       [ 8, 19, 15]])

In [40]:
#odd rows and odd cols
b[1::2 , 1::2]

array([[19,  8],
       [ 6,  1]])

In [45]:
#concatination
a = np.random.randint(1,20,[2,2])
a

array([[ 5,  2],
       [ 8, 15]])

In [46]:
b = np.random.randint(1,20,[2,4])
b

array([[ 1, 16, 19, 14],
       [ 1, 12, 16, 15]])

In [47]:
c = np.random.randint(1,20,[4,4])
c

array([[ 9,  5,  3, 12],
       [18, 15, 12, 12],
       [ 4, 14,  8,  8],
       [15,  7, 19, 12]])

In [54]:
# if the row of the mactrices are same then it can be join column wise and we call it  ----->>> axis = 1
#if the col of matrices are same then it can be join row wise and we call it ------>>> axis = 0

d = np.concatenate((a,b), axis=1) # col wise
print(d)

[[ 5  2  1 16 19 14]
 [ 8 15  1 12 16 15]]


In [56]:
np.concatenate((b,c),axis=0) # Row wise (default)

array([[ 1, 16, 19, 14],
       [ 1, 12, 16, 15],
       [ 9,  5,  3, 12],
       [18, 15, 12, 12],
       [ 4, 14,  8,  8],
       [15,  7, 19, 12]])

In [60]:
# STACK
# if column wise joined then --> hstack or horizontal stack
# if row wise joined then --> vstack or vertical stack
print(np.hstack((a,b)))
print("----------------")
print(np.vstack((b,c)))

[[ 5  2  1 16 19 14]
 [ 8 15  1 12 16 15]]
----------------
[[ 1 16 19 14]
 [ 1 12 16 15]
 [ 9  5  3 12]
 [18 15 12 12]
 [ 4 14  8  8]
 [15  7 19 12]]


In [61]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
np.diagonal(a) #prints only diagonal elements

array([1, 5, 9])

In [68]:
np.flip(a) #it will flip for both two axises

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [69]:
np.flip(a,axis=1) # flip only horizontally

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [70]:
np.diagonal(np.flip(a,axis=1))

array([3, 5, 7])

In [74]:
#PANDAS
import pandas as pd
'''
        -Pandas is a python library which is use to analyze and manipulate the data
        -We can also read and create datasets using pandas.
        -Pandas is of two types : 
            1.Sesries (Single col) --> name
            2.DataFrame (Multiple cols) --> sl no , name , roll , course 
            
'''

'\n        -Pandas is a python library which is use to analyze and manipulate the data\n        -We can also read and create datasets using pandas.\n        -Pandas is of two types : \n            1.Sesries (Single col) --> name\n            2.DataFrame (Multiple cols) --> sl no , name , roll , course \n            \n'

In [75]:
#creating series

s = pd.Series(['a','b','c','d','e'])
s

0    a
1    b
2    c
3    d
4    e
dtype: object

In [76]:
type(s)

pandas.core.series.Series

In [78]:
#using sets
s = pd.Series(['a','b','c','d','e'] , index=[10,20,30,40,50]) #length of index and values should be same
s

10    a
20    b
30    c
40    d
50    e
dtype: object

In [79]:
s[20] #indexing

'b'

In [80]:
s = pd.Series(['a','b','c','d','e'] , index=[10,20,20,40,50])
s

10    a
20    b
20    c
40    d
50    e
dtype: object

In [82]:
s[20] # it will show two values on index 20

20    b
20    c
dtype: object

In [83]:
#using tuple
t = pd.Series((10,20,30,40))
t

0    10
1    20
2    30
3    40
dtype: int64

In [86]:
#set to series
#s = pd.Series({10,20,30,40,50}) #it can't be --> type Error!
#s

In [97]:
#dictionary to Series
d = pd.Series({'a':1,'b':2,'c':3,'d':4}) # it will take key as index and value as value
d

a    1
b    2
c    3
d    4
dtype: int64

In [101]:
#indexing in dict
d['a']

1

In [102]:
d[1]

C:\Users\91732\AppData\Local\Temp\ipykernel_5920\708413107.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  d[1]


2

In [103]:
a = pd.Series({'a':1,'b':2,'c':3,'d':4},index=['e','f','g','h']) #key is always unique if once a value is assigned to a key then key cannot be changed
a

e   NaN
f   NaN
g   NaN
h   NaN
dtype: float64

In [104]:
#Slicing
d['b':'c']

b    2
c    3
dtype: int64

In [105]:
d[1:3:1]

b    2
c    3
dtype: int64