In [1]:
#NumPy
import numpy as np


In [2]:
#Creating 1D Array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
type(a) #ndArray --> n-dimensional array

numpy.ndarray

In [5]:
b = np.array([1,2,'cat',True,'40']) #this shows array is a collection of homogeneous elements
b

array(['1', '2', 'cat', 'True', '40'], dtype='<U11')

In [6]:
#tupple to array
t = np.array((10,20,30,40))
t

array([10, 20, 30, 40])

In [11]:
# set to array
s = np.array({1,2,3,4,1,4,6}) # it considers the set as one element of array
s

array({1, 2, 3, 4, 6}, dtype=object)

In [12]:
#dictionary to array
d = np.array({'a':1,'b':2,'c':3})    # it considers the set as one element of array
d

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [13]:
#Creatng 2D Array
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
#using tupple
t = np.array([(1,2,4) , (5,6,7)])
print(t)

[[1 2 4]
 [5 6 7]]


In [19]:
#a = np.array([[1,2,3],[4,5,6,6,7,8,9]]) #we cannot mismatch the array size
#a

In [21]:
a = np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])
a

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
#Array attributes
a.shape #to check shape of the array


(3, 4)

In [23]:
a.size #size of the array

12

In [24]:
a.ndim #dimension

2

In [26]:
#arange : it returns a 1D array of given range/sequence
np.arange(1,11,2)


array([1, 3, 5, 7, 9])

In [27]:
#zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((5,5)) # 0. because default datatype of array is float

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.zeros((4,4),dtype='int') #to convert datatype to integer

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [34]:
np.zeros((4,4),dtype=np.int32) #to convert datatype to integer

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [35]:
c = np.zeros((5,5)) 
c.astype('int')    #to convert datatype to integer

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [36]:
#np.ones()
np.ones((5))

array([1., 1., 1., 1., 1.])

In [37]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
#for all digits
#full
np.full((5,5),4.5)

array([[4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5]])

In [40]:
#eye --> identity matrix
np.eye(5,dtype = 'int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [44]:
#linspace - equally distributed numbers 
np.linspace(1,100,10)   #here range is 1 to 100 and wanted number is 10 --> it will print 10 random numbers between 1 to 100 

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [45]:
#random numbers 
np.random.rand() #it will return random values between 0 to 1

0.6378022952498228

In [47]:
np.random.rand(4) #it will return a 1D array of 4 random numbers betweeen 0 to 1

array([0.07256541, 0.21065382, 0.04357191, 0.92838287])

In [48]:
np.random.rand(4,4) #it will return a 2D array 4x4 betweeen 0 to 1

array([[0.17178262, 0.43898269, 0.21322961, 0.93234853],
       [0.67404637, 0.19663762, 0.37382401, 0.46119537],
       [0.38506402, 0.53377258, 0.88683243, 0.62662217],
       [0.46127786, 0.93081617, 0.13499827, 0.66266063]])

In [50]:
np.random.randint(1,20) #returns random value between 1 to 20 in integer

16

In [51]:
np.random.randint(1,20,(4,4)) #returns 2D array of random value between 1 to 20 in integer

array([[ 4, 16, 11, 15],
       [ 3, 12,  4,  3],
       [14, 18,  2,  8],
       [ 1, 15, 17, 11]])

In [53]:
#mathematical operations
a = np.array([1,2,3,4,5])
b = np.array([7,8,9,1,6])
print(a)
print(b)

[1 2 3 4 5]
[7 8 9 1 6]


In [54]:
np.add(a,b)

array([ 8, 10, 12,  5, 11])

In [56]:
np.subtract(b,a)

array([ 6,  6,  6, -3,  1])

In [57]:
np.multiply(a,b)

array([ 7, 16, 27,  4, 30])

In [58]:
np.divide(b,a)

array([7.  , 4.  , 3.  , 0.25, 1.2 ])

In [62]:
np.mod(b,a) #modulus or remainder

array([0, 0, 0, 1, 1])

In [63]:
np.floor_divide(b,a)

array([7, 4, 3, 0, 1])

In [64]:
np.divmod(b,a) #it returns both floor division and remainder 

(array([7, 4, 3, 0, 1]), array([0, 0, 0, 1, 1]))

In [65]:
np.reciprocal(a)

array([1, 0, 0, 0, 0])

In [66]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [67]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [68]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [2]:
#np.log(a)

In [70]:
#statistical fuctional
np.max(a)

5

In [69]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [71]:
np.min(a)

1

In [72]:
np.mean(a)

3.0

In [73]:
np.median(a)

3.0

In [74]:
#Standard deviation
np.std(a)

1.4142135623730951

In [75]:
#Variance
np.var(a)

2.0

In [77]:
a

array([1, 2, 3, 4, 5])

In [78]:
#cumulative summation --> cumsum
np.cumsum(a)

array([ 1,  3,  6, 10, 15])

In [79]:
#repeat
a = np.array([1,2,3,4,5])
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5])

In [82]:
#tile
a = np.array([1,2,3,4])
np.tile(a,4)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [83]:
#where
a = np.array([1,2,4,4,3,4,2,4,5,6,3,4])
np.where(a==4)

(array([ 2,  3,  5,  7, 11], dtype=int64),)

In [84]:
#argmax --> max value index
np.argmax(a)

9

In [85]:
#argmin
np.argmin(a)

0